### ISSUE TITLE
cannot delete or edit server

### ISSUE THREAD

**Issue by pakleonghui** [justdave/MCStatus#8] opened 2015-12-22 13:54 UTC
cannot delete or edit server

**Comment by justdave** [comment] 2015-12-22 14:10
What happens when you try? Are you getting an error?

**Comment by pakleonghui** [comment] 2015-12-23 09:39
No

**Comment by pakleonghui** [comment] 2015-12-23 09:48
When I test the app on emulator , I can delete or edit server ,but when I test on my mobile phone(lenovo A7000) the bug occour

**Comment by justdave** [comment] 2015-12-23 12:42
You still haven't answered the question. What happens when you try to edit or delete?  Does it not allow you to select a server? Can you select it but the toolbar doesn't show up? Do you get a toolbar but tapping the icons on it doesn't do anything? etc.

**Comment by justdave** [comment] 2016-01-29 16:16
@pakleonghui any answer? Otherwise I'll close this as "can't reproduce" soon

**Closed** 2016-03-02 21:55 UTC
Labels: invalid
